# Generated by Django 4.0.3 on 2022-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('Car_Id', models.CharField(max_length=255)),
                ('Car_Name', models.CharField(max_length=255)),
                ('Car_Description', models.CharField(max_length=255)),
                ('Car_Rental_Price', models.CharField(max_length=255)),
                ('CarImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('Car_borrow_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=1000)),
                ('message_id', models.CharField(max_length=255)),
                ('message_created_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('user_type', models.CharField(default=1, max_length=1)),
                ('renter', models.CharField(blank=True, max_length=255, null=True)),
                ('borrower', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('dropoff_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pickup_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('rent_number', models.CharField(max_length=255)),
                ('order_date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
