# Generated by Django 4.0.3 on 2022-05-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowcar',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentcar',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrowcar',
            name='CarImage',
            field=models.FileField(upload_to='file'),
        ),
        migrations.AlterField(
            model_name='content',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
