# Generated by Django 4.0.3 on 2022-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0002_borrowcar_email_rentcar_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowcar',
            name='CarImage',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='message_created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
