# Generated by Django 4.0.3 on 2022-05-07 16:28

import DjangoWeb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0003_alter_borrowcar_carimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcar',
            name='pickup_time',
        ),
        migrations.AlterField(
            model_name='borrowcar',
            name='CarImage',
            field=models.ImageField(blank=True, null=True, upload_to=DjangoWeb.models.filepath),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='dropoff_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='pickup_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
