# Generated by Django 4.0.3 on 2022-05-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0004_remove_rentcar_pickup_time_alter_borrowcar_carimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='message_id',
        ),
    ]
