# Generated by Django 4.0.3 on 2022-05-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0006_remove_profile_borrower_remove_profile_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcar',
            name='phone',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
