# Generated by Django 4.0.3 on 2022-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0007_rentcar_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcar',
            name='dropoff_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='pickup_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
